platform :ios, '8.0'
use_frameworks!

target 'PublicFloat' do
  pod 'AFNetworking', '~> 2.5'
  pod 'ORStackView', '~> 2.0'
  pod 'SwiftyJSON', '~> 2.1'
  pod 'RxSwift'
  pod 'RxCocoa'
end

target 'PublicFloatTests' do
    pod 'Quick', '~> 0.3.0'
    pod 'Nimble', '~> 1.0.0'
end
